### PR TITLE
Fix tests for platforms other than Windows

### LINKED ISSUE #37: mongo2go linux netcore 1.1
Hello,

I have an issue with mongo2go in a linux environment, using the 2.0.0-aplha1 version.
the method MakeFileExecutable() throws an exception :

```
Invalid File or Directory attributes value
           at System.IO.FileSystemInfo.System.IO.IFileSystemObject.set_Attributes(FileAttributes value)
           at System.IO.UnixFileSystem.SetAttributes(String fullPath, FileAttributes attributes)
           at System.IO.File.SetAttributes(String path, FileAttributes fileAttributes)
        /data/projects/Mongo2Go/src/Mongo2Go/Helper/FileSystem.cs(35,0): at Mongo2Go.Helper.FileSystem.MakeFileExecutable(String path)
        /data/projects/Mongo2Go/src/Mongo2Go/MongoDbRunner.cs(137,0): at Mongo2Go.MongoDbRunner.MakeMongoBinarysExecutable()
        /data/projects/Mongo2Go/src/Mongo2Go/MongoDbRunner.cs(120,0): at Mongo2Go.MongoDbRunner..ctor(IPortPool portPool, IFileSystem fileSystem, IMongoDbProcessStarter processStarter, IMongoBinaryLocator mongoBin, String dataDirectory)
        /data/projects/Mongo2Go/src/Mongo2Go/MongoDbRunner.cs(37,0): at Mongo2Go.MongoDbRunner.Start(String dataDirectory, String searchPatternOverride)
```
if I comment this line, everything works as excepted.

Thanks

### PR DESCRIPTION
**Pull request by perliedman**
This fixes #37 (1515dda043af41e88345b053b2f810cf3670b24f), but also makes the tests run on Linux (and hopefully also OS X).

A lot of paths were hardcoded to use backslash as path separator, which doesn't work on Linux, and also the data path defaulted to use `C:\data\`, which obviously doesn't work on Linux.

This PR make the somewhat intrusive change of removing the `MongoDbDefaults.DataDirectory` constant, and will instead by default create the database in the user's temporary directory, which I think is a better default, although I guess it could be debated.

### CODE REVIEW

**Comment by JohannesHoppe** [comment]
Yay! I 👍  will look at this soon. Did you tested it on windows, too?
The user's temporary directory is fine for me.

**Comment by perliedman** [comment]
@JohannesHoppe will test on Windows as well and get back to you!

File: src/Mongo2Go/Helper/FileSystem.cs [hunk 1]
```diff
@@ -31,7 +32,13 @@ public void DeleteFile(string fullFileName)
         public void MakeFileExecutable (string path) 
         {
             //when on linux or osx we must set the executeble flag on mongo binarys
-            File.SetAttributes (path, (FileAttributes)((int)File.GetAttributes (path) | 0x80000000));
+            var p = Process.Start("chmod", $"+x {path}");
```
Comment (JohannesHoppe) [inline src/Mongo2Go/Helper/FileSystem.cs]: Windows?! :-(

Comment (perliedman) [reply src/Mongo2Go/Helper/FileSystem.cs]: I did run them on Linux, but I confess I fiddled a bit with the project settings to build it for .NET Core 2.0 instead - since that change did a lot of stuff I wasn't sure you actually liked, I kept it out of this PR.

I'm of course happy to submit a separate PR with these changes as well, it might be that some of them are applicable for you.

Re: `MakeFileExecutable`, I think that code is only executed for Linux as it is (https://github.com/Mongo2Go/Mongo2Go/blob/master/src/Mongo2Go/MongoDbRunner.cs#L135), but to be sure we could have a test and run separate code paths for different OS

Comment (JohannesHoppe) [reply src/Mongo2Go/Helper/FileSystem.cs]: You are absolutely right. I did a quick lookup and haven't seen `RuntimeInformation.IsOSPlatform(OSPlatform.Linux)`. We might want to rename the method from `MakeFileExecutable` to `MakeFileExecutableForLinux`! 😄

Comment (JohannesHoppe) [reply src/Mongo2Go/Helper/FileSystem.cs]: >  to build it for .NET Core 2.0 instead
So you wanted to go from `<TargetFramework>netstandard1.6</TargetFramework>` to `<TargetFramework>netcoreapp2.0</TargetFramework>`. Are there any benefits for you to do that?!

Comment (perliedman) [reply src/Mongo2Go/Helper/FileSystem.cs]: Not entirely sure what I'm doing, I find the combination of versions in the new MS world very confusing! 😄 

As you can see in #44, I updated the test project from `netcoreapp1.0` to `netcoreapp2.0`, but it might be that some version in between works as well...

**Comment by perliedman** [comment]
I've run this branch, together with #44, on Windows as well, and all tests pass.

So, in summary: with #42 and #44, all tests run successfully on Linux _and_ Windows.

File: src/Mongo2Go/Helper/FileSystem.cs (hunk 1 above)
Comment (JohannesHoppe) [reply src/Mongo2Go/Helper/FileSystem.cs]: Yeah. Versions. You will get used to that. It makes sense in the end... 😕 😄 

Having the Tests in `netcoreapp2.0` is no breaking change at all. If they run again, that will be a bug benefit! Great! :-)

**Comment by JohannesHoppe** [comment]
I will review & test #42 and #44 this evening.

File: src/Mongo2Go/Helper/FileSystem.cs (hunk 1 above)
Comment (tomh3000) [reply src/Mongo2Go/Helper/FileSystem.cs]: I have made the chmod change locally (I have not got round to creating a PR) and it is working fine on Linux. I also renamed the method to MakeFileExecutableForLinux!

**Comment by JohannesHoppe** [comment]
Man this took more time than expected. New nuget packages might come tomorrow. I need to work! ;-)

**Comment by perliedman** [comment]
@JohannesHoppe I know the feeling! :smile: Thanks for quick review and merge - I know from personal experience that reviewing PRs can take a lot more time than contributors might think.

Also thanks for all the other work with Mongo2Go, it has been a really quick way for us to get integration tests going in a big project we're working on.

**Comment by JohannesHoppe** [comment]
Thx! Glad to hear that! 😄

File: src/Mongo2Go/Helper/FileSystem.cs (hunk 1 above)
Comment (JohannesHoppe) [reply src/Mongo2Go/Helper/FileSystem.cs]: I also added the `chmod` for macOS. Does anybody here has a Mac!?

**Comment by JohannesHoppe** [comment]
I pushed `v2.2.1` to nuget.org. Could you please test it?

**Comment by perliedman** [comment]
@JohannesHoppe Works flawlessly :+1: Thanks again!
